# Tracker.action
# Goal
custom_drone_interfaces/Waypoint current_waypoint  # Waypoint containing subWaypoints with heading, position, velocity and acceleration data
---
# Result
bool success         # True if path was successfully followed
---
# Feedback
custom_drone_interfaces/Waypoint current_remaining_waypoint   # Current UAV pose
bool status_executing